# -*- coding: utf-8 -*-
"""factorail

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-bINoub5Z-LFlP-pRTxTLrQcJRWmLNml
"""

# Factorial of a number

n = int(input("Enter a number: "))

factorial = 1

for i in range(1, n + 1):
    factorial = factorial * i

print("Factorial of", n, "is", factorial)