# -*- coding: utf-8 -*-
"""fibonacci

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pAl9X_M7yoZJ1pJxfWLsA2iTrNLTTcmw
"""

# Fibonacci series

n = int(input("Enter the number of terms: "))

a = 0
b = 1

print("Fibonacci series:")

for i in range(n):
    print(a, end=" ")
    a, b = b, a + b